; ESP32-2424S012C – ESP32-C3 + 1.28" rundes GC9A01-Display (240x240) + CST816D-Touch

[env:esp32-2424S012C]
platform = espressif32@^6.9.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
monitor_filters = esp32_exception_decoder
build_flags =
    ; Serial über die native USB-Schnittstelle des C3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    lovyan03/LovyanGFX@^1.2.0
